// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUbTfcp6M9-WLSlVfaLUF0BYo84KwnPs',
    appId: '1:665118661577:web:19169fa3e4c3e07a1c2618',
    messagingSenderId: '665118661577',
    projectId: 'authantisolo',
    authDomain: 'authantisolo.firebaseapp.com',
    storageBucket: 'authantisolo.firebasestorage.app',
    measurementId: 'G-5G8MFKV8NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqXqieRqPQTR4YF9sl-E8fcOnD7cI_X_E',
    appId: '1:665118661577:android:99856520ee4deb6d1c2618',
    messagingSenderId: '665118661577',
    projectId: 'authantisolo',
    storageBucket: 'authantisolo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApYbX_CrQVUeIZmOdC3fvyctH3csK5mnA',
    appId: '1:665118661577:ios:95601b370f6bc0f81c2618',
    messagingSenderId: '665118661577',
    projectId: 'authantisolo',
    storageBucket: 'authantisolo.firebasestorage.app',
    iosClientId: '665118661577-6qtj4ec5lhs723r6da443ggeu05pbgbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.finetuneduniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApYbX_CrQVUeIZmOdC3fvyctH3csK5mnA',
    appId: '1:665118661577:ios:95601b370f6bc0f81c2618',
    messagingSenderId: '665118661577',
    projectId: 'authantisolo',
    storageBucket: 'authantisolo.firebasestorage.app',
    iosClientId: '665118661577-6qtj4ec5lhs723r6da443ggeu05pbgbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.finetuneduniverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzUbTfcp6M9-WLSlVfaLUF0BYo84KwnPs',
    appId: '1:665118661577:web:19169fa3e4c3e07a1c2618',
    messagingSenderId: '665118661577',
    projectId: 'authantisolo',
    authDomain: 'authantisolo.firebaseapp.com',
    storageBucket: 'authantisolo.firebasestorage.app',
    measurementId: 'G-5G8MFKV8NY',
  );
}
